addons:
  apt:
    packages:
    - enchant
language: python
python:
- '3.8'
before_install:
- travis_retry pip install --upgrade pip setuptools codecov
install:
- travis_retry pip install --upgrade --editable .[dev]
cache: pip
script:
- make lint
- make build-sample
- pytest -s -vvv --cov-fail-under 100 --cov=src/ --cov=tests tests/
after_success:
- codecov
