language: python
python:
- '3.5'
before_install:
- travis_retry pip install --upgrade pip setuptools codecov
install:
- travis_retry pip install --upgrade --editable .[dev]
cache: pip
script:
- pytest -s -vvv --cov=src/ --cov=tests tests/
after_success:
- codecov
