---

# The normal CI run tests with the latest dependency versions.
# This tests with the oldest versions.
# We assume that everything in between will work if these two work.
#
name: CI Versions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 1:00 every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # We do not use the cache action as uv is faster than the cache action.
      - name: "Install dependencies"
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv /home/runner/.venv
          source /home/runner/.venv/bin/activate
          uv pip install --upgrade --editable ".[dev]"
          # Oldest versions from requirements.
          # Ideally we would use --resolution=lowest but it does not work -
          # https://github.com/astral-sh/uv/issues/1563
          pip install Sphinx==7.2.0
          pip install sphinx-prompt==1.8.0
          pip install docutils==0.19

      - name: "Build sample"
        run: |
          source /home/runner/.venv/bin/activate
          make build-sample

      - name: "Run tests"
        run: |
          source /home/runner/.venv/bin/activate
          pytest -s -vvv --cov-fail-under 100 --cov=src/ --cov=tests tests/ --cov-report=xml

      - name: "Upload coverage to Codecov"
        uses: "codecov/codecov-action@v4"
